### ISSUE TITLE
Error occurring on build of HCA

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#457]
As per our conversation yesterday, the following error is occurring when building HCA:

```
> Build error occurred
TypeError: Cannot read properties of undefined (reading 'next')
    at service_listAll (/Users/bruce/dev/git/clevercanary/data-browser/explorer/.next/server/chunks/125.js:319:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/bruce/dev/git/clevercanary/data-browser/explorer/.next/server/pages/[slug]/[...params].js:55:26
    at async Promise.all (index 0)
    at async getStaticPaths (/Users/bruce/dev/git/clevercanary/data-browser/explorer/.next/server/pages/[slug]/[...params].js:51:19)
    at async buildStaticPaths (/Users/bruce/dev/git/clevercanary/data-browser/explorer/node_modules/next/dist/build/utils.js:491:31)
    at async /Users/bruce/dev/git/clevercanary/data-browser/explorer/node_modules/next/dist/build/utils.js:632:119
    at async Span.traceAsyncFn (/Users/bruce/dev/git/clevercanary/data-browser/explorer/node_modules/next/dist/trace/trace.js:79:20) {
  type: 'TypeError'
}
```

**Comment by BruceRodrigues** [comment]
I will keep this on standby for a while. I was trying to debug the error to find out what's happening, but now I can't reproduce it anymore

**Comment by BruceRodrigues** [comment]
Can't reproduce.
